// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package accountsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	// ClassifyTwitterAccount classifies a single TwitterAccount
	// returns a ResponseAccount message
	ClassifyTwitterAccount(ctx context.Context, in *TwitterAccount, opts ...grpc.CallOption) (*ResponseAccount, error)
	// ClassifyTwitterAccount classifies a list of TwitterAccount messages (TwitterAccountList)
	// returns a list of ResponseAccount messages (ResponseAccountList)
	ClassifyTwitterAccounts(ctx context.Context, in *TwitterAccountList, opts ...grpc.CallOption) (*ResponseAccountList, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) ClassifyTwitterAccount(ctx context.Context, in *TwitterAccount, opts ...grpc.CallOption) (*ResponseAccount, error) {
	out := new(ResponseAccount)
	err := c.cc.Invoke(ctx, "/proto.rtaa.classification.accounts.v1.AccountService/ClassifyTwitterAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ClassifyTwitterAccounts(ctx context.Context, in *TwitterAccountList, opts ...grpc.CallOption) (*ResponseAccountList, error) {
	out := new(ResponseAccountList)
	err := c.cc.Invoke(ctx, "/proto.rtaa.classification.accounts.v1.AccountService/ClassifyTwitterAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations should embed UnimplementedAccountServiceServer
// for forward compatibility
type AccountServiceServer interface {
	// ClassifyTwitterAccount classifies a single TwitterAccount
	// returns a ResponseAccount message
	ClassifyTwitterAccount(context.Context, *TwitterAccount) (*ResponseAccount, error)
	// ClassifyTwitterAccount classifies a list of TwitterAccount messages (TwitterAccountList)
	// returns a list of ResponseAccount messages (ResponseAccountList)
	ClassifyTwitterAccounts(context.Context, *TwitterAccountList) (*ResponseAccountList, error)
}

// UnimplementedAccountServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAccountServiceServer struct {
}

func (UnimplementedAccountServiceServer) ClassifyTwitterAccount(context.Context, *TwitterAccount) (*ResponseAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyTwitterAccount not implemented")
}
func (UnimplementedAccountServiceServer) ClassifyTwitterAccounts(context.Context, *TwitterAccountList) (*ResponseAccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyTwitterAccounts not implemented")
}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_ClassifyTwitterAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwitterAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ClassifyTwitterAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rtaa.classification.accounts.v1.AccountService/ClassifyTwitterAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ClassifyTwitterAccount(ctx, req.(*TwitterAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ClassifyTwitterAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwitterAccountList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ClassifyTwitterAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rtaa.classification.accounts.v1.AccountService/ClassifyTwitterAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ClassifyTwitterAccounts(ctx, req.(*TwitterAccountList))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.rtaa.classification.accounts.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyTwitterAccount",
			Handler:    _AccountService_ClassifyTwitterAccount_Handler,
		},
		{
			MethodName: "ClassifyTwitterAccounts",
			Handler:    _AccountService_ClassifyTwitterAccounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rtaa/classification/accounts/v1/accounts.proto",
}
