// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package commentsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentServiceClient is the client API for CommentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentServiceClient interface {
	ClassifyToxic(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*ResponseToxic, error)
	ClassifyToxicList(ctx context.Context, in *CommentList, opts ...grpc.CallOption) (*ResponseToxicList, error)
}

type commentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentServiceClient(cc grpc.ClientConnInterface) CommentServiceClient {
	return &commentServiceClient{cc}
}

func (c *commentServiceClient) ClassifyToxic(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*ResponseToxic, error) {
	out := new(ResponseToxic)
	err := c.cc.Invoke(ctx, "/proto.rtaa.classification.comments.v1.CommentService/ClassifyToxic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commentServiceClient) ClassifyToxicList(ctx context.Context, in *CommentList, opts ...grpc.CallOption) (*ResponseToxicList, error) {
	out := new(ResponseToxicList)
	err := c.cc.Invoke(ctx, "/proto.rtaa.classification.comments.v1.CommentService/ClassifyToxicList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentServiceServer is the server API for CommentService service.
// All implementations should embed UnimplementedCommentServiceServer
// for forward compatibility
type CommentServiceServer interface {
	ClassifyToxic(context.Context, *Comment) (*ResponseToxic, error)
	ClassifyToxicList(context.Context, *CommentList) (*ResponseToxicList, error)
}

// UnimplementedCommentServiceServer should be embedded to have forward compatible implementations.
type UnimplementedCommentServiceServer struct {
}

func (UnimplementedCommentServiceServer) ClassifyToxic(context.Context, *Comment) (*ResponseToxic, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyToxic not implemented")
}
func (UnimplementedCommentServiceServer) ClassifyToxicList(context.Context, *CommentList) (*ResponseToxicList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassifyToxicList not implemented")
}

// UnsafeCommentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentServiceServer will
// result in compilation errors.
type UnsafeCommentServiceServer interface {
	mustEmbedUnimplementedCommentServiceServer()
}

func RegisterCommentServiceServer(s grpc.ServiceRegistrar, srv CommentServiceServer) {
	s.RegisterService(&CommentService_ServiceDesc, srv)
}

func _CommentService_ClassifyToxic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ClassifyToxic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rtaa.classification.comments.v1.CommentService/ClassifyToxic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ClassifyToxic(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommentService_ClassifyToxicList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentServiceServer).ClassifyToxicList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rtaa.classification.comments.v1.CommentService/ClassifyToxicList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentServiceServer).ClassifyToxicList(ctx, req.(*CommentList))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentService_ServiceDesc is the grpc.ServiceDesc for CommentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.rtaa.classification.comments.v1.CommentService",
	HandlerType: (*CommentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClassifyToxic",
			Handler:    _CommentService_ClassifyToxic_Handler,
		},
		{
			MethodName: "ClassifyToxicList",
			Handler:    _CommentService_ClassifyToxicList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rtaa/classification/comments/v1/comments.proto",
}
